org: 12ccs
app: test-nest
service: test-nest
frameworkVersion: '3'

plugins:
  - serverless-plugin-warmup
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin

useDotenv: true

custom:
  stage: ${opt:stage, 'prod'}
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules: false
  dotenv:
    path: environments/.env.${self:custom.stage}
    logging: false
  warmup:
    default:
      enabled: ${self:custom.enableWarmup, false}
      events:
        - schedule: cron(0/10 * ? * MON-FRI *)
      concurrency: 1
      logRetentionInDays: 14

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  memorySize: 1024
  timeout: 30
  region: us-east-1
  logRetentionInDays: 7

package:
  individually: true

functions:
  main:
    handler: src/entrypoints/api-entrypoint.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: any
          path: /{proxy+}
          cors: true

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: custom-storage-${self:custom.stage}
