org: 12ccs
app: test-nest
service: test-nest

frameworkVersion: '3'

plugins:
  - serverless-plugin-warmup
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

package:
  individually: true

functions:
  main:
    handler: src/entrypoints/api-entrypoint.handler
    timeout: 300
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true

custom:
  stage: ${opt:stage, "prod"}
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules: false
  dotenv:
    path: environments/.env.${self:custom.stage}
    logging: false
  warmup:
    officeHoursWarmer:
      enabled: false
      events:
        - schedule: cron(0/5 8-17 ? * MON-FRI *)
      concurrency: 10
      verbose: true
      logRetentionInDays: 7
    outOfOfficeHoursWarmer:
      enabled: false
      events:
        - schedule: cron(0/5 0-7 ? * MON-FRI *)
        - schedule: cron(0/5 18-23 ? * MON-FRI *)
        - schedule: cron(0/5 * ? * SAT-SUN *)
      concurrency: 1
      verbose: false
    testWarmer:
      enabled: false