version: '3.8'

services:
  db:
    container_name: "${DOCKER_CONTAINER_NAME}"
    ports:
      - "${DB_HOST_PORT}:1433"
    build: 
      context: .
      dockerfile: "Dockerfile"
      args:
        SA_PASSWORD: "${DB_HOST_PASSWORD}"
